name = "bakwan"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "35.219.50.99"
UUID = "6b946778-4777-46cb-aee2-8f8a39bf700f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
